ServerRoot   "/etc/httpd"
Listen   80

LoadModule   rewrite_module   modules/mod_rewrite.so
LoadModule   mime_module   modules/mod_mime.so

User   apache
Group   apache
ServerAdmin   root@localhost
ServerName   www.example.com:80

<Directory   />
    AllowOverride   none
    Require   all   denied
</Directory>

DocumentRoot   "/var/www/html"

<Directory   "/var/www/html">
    Options   Indexes   FollowSymLinks
    AllowOverride   All
    Require   all   granted
</Directory>

<IfModule   dir_module>
    DirectoryIndex   index.html   index.htm
</IfModule>

ErrorLog   "logs/error_log"
LogLevel   warn

<IfModule   log_config_module>
    LogFormat   "%h %l %u %t \"%r\" %>s %b \"keep  two spaces\""   common
    CustomLog   "logs/access_log"   common
</IfModule>

KeepAlive   On
Timeout   60
